version: '3.4'

services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: db_motorcyclerent
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped    

  rabbitmq:    
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq    
    restart: unless-stopped

  motorcyclerental.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__MotorcycleRentDb=Server=postgres;Port=5432;User Id=root;Password=root;Database=db_motorcyclerent;
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@localhost/
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - postgres
    depends_on:
      - postgres 